# Generated by Django 3.2.6 on 2021-08-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
